if (LINUX)

    set(LINUX_APPDIR_PATH "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.AppDir")
    set(LINUX_APPDIR_PREFIX "usr")
    
    set(LINUX_APPDIR_BIN_DIR "${LINUX_APPDIR_PATH}/${LINUX_APPDIR_PREFIX}/bin")
    set(LINUX_APPDIR_LIB32_DIR "${LINUX_APPDIR_PATH}/${LINUX_APPDIR_PREFIX}/lib32")
    set(LINUX_APPDIR_LIB64_DIR "${LINUX_APPDIR_PATH}/${LINUX_APPDIR_PREFIX}/lib64")
    set(LINUX_APPDIR_SHARE_DIR "${LINUX_APPDIR_PATH}/${LINUX_APPDIR_PREFIX}/share")

    add_custom_command(TARGET ${PROJECT_NAME} PRE_BUILD 
        COMMAND ${CMAKE_COMMAND} -E make_directory "${LINUX_APPDIR_PATH}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${LINUX_APPDIR_PATH}/${LINUX_APPDIR_PREFIX}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${LINUX_APPDIR_BIN_DIR}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${LINUX_APPDIR_LIB32_DIR}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${LINUX_APPDIR_LIB64_DIR}"
        COMMAND ${CMAKE_COMMAND} -E make_directory "${LINUX_APPDIR_SHARE_DIR}"
    )

    set(APPIMAGE_DESKTOP_PATH "\"${PROJECT_RESOURCES_DIR}/Linux/Sonic The Hedgehog (SMS).desktop\"")
    set(APPIMAGE_APPRUN_PATH "${PROJECT_RESOURCES_DIR}/Linux/AppRun")

    add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD 
        COMMAND ${CMAKE_COMMAND} -E copy ${APPIMAGE_DESKTOP_PATH} ${APPIMAGE_APPRUN_PATH} ${CMAKE_BINARY_DIR}/${PROJECT_NAME}.AppDir
        COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:${PROJECT_NAME}> "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.AppDir/usr/bin"
        #COMMAND ${CMAKE_COMMAND} -E copy ${RAYLIB_LIBS} "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.AppDir/usr/lib"
        #COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_ASSETS} "${CMAKE_BINARY_DIR}/${PROJECT_NAME}.AppDir/usr/share/res"
    )


endif()